url: 'styles-library.dev'
folders:
  css: 'wwwroot/css/'
  documentation: 'wwwroot/documentation/'
  fonts: 'wwwroot/fonts/'
  icons: 'wwwroot/icons/'
  imageSrc: 'images/'
  images: 'wwwroot/images/'
  js: 'wwwroot/js/'
  jsMolecules: 'jsSrc/molecules/'
  jsSrc: 'jsSrc/'
  root: 'wwwroot/'
  scss: 'styles/scss/'
  svg: 'svg/'
  svgMin: 'svg/min/'
