url: 'styles-library.dev'
folders:
  css: 'wwwroot/css/'
  fonts: 'wwwroot/fonts/'
  icons: 'wwwroot/icons/'
  images: 'wwwroot/images/'
  js: 'wwwroot/js/'
  jsComp: 'jsSrc/components/'
  jsSrc: 'jsSrc/'
  scss: 'scss/'
  svg: 'svg/'
  svgMin: 'svg/min/'
